config/routes.rb
Nspeed::Application.routes.draw do
  mount RailsAdmin::Engine => '/super_admin', :as => 'rails_admin'

  devise_for :users

  resources :receiving

  resources :projects do
    resources :documents do
      get 'by_requirement', :on => :collection
      resources :document_assets
    end
    resources :materials do
      resources :material_invoices
    end
    resources :submittals
    resources :material_types
    resources :material_lists
  end

  namespace :admin do
    resources :companies
  end

  namespace :company_admin do
    resource :dashboard
    resources :projects do
      resources :project_requirements
      resources :submittal_statuses
      resources :prerequisites
      resources :project_people do
        collection do
          post 'save'
        end
        member do
          delete 'remove'
        end
      end
      get 'roles'
    end
    resources :customers
    resources :project_types
    resources :roles
    resources :users
    resources :material_types
  end

  resources :custom_fields
  root :to => 'dashboard#index'

end

app/controllers/company_admin/company_admin_controller.rb
class CompanyAdmin::CompanyAdminController < ApplicationController

  before_filter :authorize_admin_user

  def authorize_admin_user
    unless (is_super_admin? || is_company_admin?)
      redirect_to root_url, notice: "You aren't authorized."
    end
  end


end

app/controllers/company_admin/customers_controller.rb
class CompanyAdmin::CustomersController < CompanyAdmin::CompanyAdminController
  expose(:company) { current_user.company }
  expose(:customers) { company.customers.paginate(:page => params[:page]) }
  expose(:customer) {
    if params[:id].blank?
      Customer.new
    else
      company.customers.find(params[:id])
    end
  }

  def index

  end

  def show
  end

  def new
  end

  def create
    company.customers << customer
    if company.save
      redirect_to company_admin_customers_path, :notice => "Customer #{customer.name} was created successfully!"
    else
      render :new
    end
  end

  def edit
    customer = company.customers.find(params[:id])
  end

  def update
    if customer.update_attributes(params[:customer])
      redirect_to company_admin_customers_path, :notice => "Customer #{customer.name} was updated successfully!"
    else
      render :edit
    end
  end

  def destroy

  end
end

app/controllers/company_admin/dashboards_controller.rb
class CompanyAdmin::DashboardsController < CompanyAdmin::CompanyAdminController
  def show
  end
end

app/controllers/company_admin/prerequisites_controller.rb
class CompanyAdmin::PrerequisitesController < CompanyAdmin::CompanyAdminController
  expose(:company) { current_user.company}
  expose(:project)

  expose(:prerequisites) {project.prerequisites}
  expose(:prerequisite)

  def index
  end

  def new
  end

  def create
    project.prerequisites << prerequisite
    if project.save
      redirect_to company_admin_project_prerequisites_url(project), :notice => "Prerequisite #{prerequisite.name} was created successfully!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if prerequisite.update_attributes(params[:prerequisite])
      redirect_to company_admin_project_prerequisites_url(project), :notice => "Prerequisite #{prerequisite.name} was updated successfully!"
    else
      render :edit
    end
  end

  def destroy
    prerequisite.destroy
    redirect_to company_admin_project_prerequisites_url(project), :notice => "Prerequisite #{prerequisite.name} was deleted successfully!"
  end
end

app/controllers/company_admin/project_people_controller.rb
class CompanyAdmin::ProjectPeopleController < CompanyAdmin::CompanyAdminController
  expose(:company) { current_user.company }
  expose(:project)

  expose(:all_people) { Person.not_in_project(project) }
  expose(:people) { project.people }
  expose(:person)

  def index
  end

  def save
    params[:ids].each do |id|
      unless project.people.exists?(id)
        project.people << Person.find(id)
      end
    end
    project.save

    redirect_to company_admin_project_project_people_url, :notice => "People were added successfully to the project."
  end

  def remove
    removed_person = project.people.find(params[:id])
    project.people.destroy(params[:id])
    project.save
    redirect_to company_admin_project_project_people_url, :notice => "#{removed_person.first_name} #{removed_person.last_name} was removed successfully."
  end
end

app/controllers/company_admin/project_requirements_controller.rb
class CompanyAdmin::ProjectRequirementsController < CompanyAdmin::CompanyAdminController
  expose(:company) { current_user.company }
  expose(:project)
  expose(:prerequisites) { project.prerequisites }

  expose(:project_requirements) { project.project_requirements }
  expose(:project_requirement)

  def index
  end

  def new
  end

  def create
    project.project_requirements << project_requirement
    if project.save
      redirect_to company_admin_project_project_requirements_url(project), :notice => "Requirement #{project_requirement.name} was created successfully!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if project.update_attributes(params[:project_requirement])
      redirect_to company_admin_project_project_requirements_url(project), :notice => "Requirement #{project_requirement.name} was updated successfully!"
    else
      render :new
    end
  end

  def destroy
    project_requirement.destroy
    redirect_to company_admin_project_project_requirements_url(project), :notice => "Requirement #{project_requirement.name} was deleted successfully!"
  end
end

app/controllers/company_admin/project_types_controller.rb
class CompanyAdmin::ProjectTypesController < CompanyAdmin::CompanyAdminController
  expose(:company) {current_user.company}
  expose(:project_types) {company.project_types.paginate(:page => params[:page])}
  expose(:project_type)

  def index
  end

  def show
  end

  def new
  end

  def create
    company.project_types << project_type
    if company.save
      redirect_to company_admin_project_types_url, :notice => "Project Type #{project_type.name} was created successfully!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if project_type.update_parameters[:project_type]
      redirect_to company_admin_project_types_url, :notice => "Project Type #{project_type.name} was created successfully!"
    else
      render :edit
    end
  end

  def destroy
  end
end

app/controllers/company_admin/projects_controller.rb
class CompanyAdmin::ProjectsController < CompanyAdmin::CompanyAdminController

  expose(:company) {current_user.company}
  expose(:project_types) {company.project_types.order(:name)}
  expose(:customers) {company.customers.order(:name)}
  expose(:projects) {company.projects.order(:name)}
  expose(:project)

  def index
  end

  def show
    
  end

  def new
  end

  def create
    company.projects << project
    if company.save
      save_roles
      redirect_to company_admin_projects_url, :notice => "Project #{project.name} was created successfully!"
    else
      render :new
    end
  end

  def edit
  end

  def update

    project_id = project.id # save for later
    result = false
    project.transaction do
      save_roles
      result = project.update_attributes(params[:project])
    end

    project = Project.find(project_id) # refresh the roles
    if result
      redirect_to company_admin_projects_url, :notice => "Project #{project.name} was updated successfully!"
    else
      render :new
    end
  end

  def destroy
    
  end


  def roles
    if params[:term]
      @roles = Role.find(:all,:conditions => ['company_id = ? AND name LIKE ?', company.id, "%#{params[:term]}%"]).map{|x| {:id => x.id, :name => x.name, :mode => :read}}
    else
      @roles = Role.all
    end

    respond_to do |format|
      format.json { render :json => @roles.to_json(:only =>[:id, :name, :mode]) }
    end
  end


  protected

  def save_roles
    project.roles = []
    RoleResource.where(:resource_id => project).where(:resource_type => 'Project').delete_all
    unless params["table_roles_field_id"].nil?
      i = 0
      while i < params["table_roles_field_id"].length do
        RoleResource.create(:role_id => params["table_roles_field_id"][i], :mode => params["table_roles_field_mode"][i], :resource_id => project.id, :resource_type => "Project")
        i += 1
      end
    end
  end
end

app/controllers/company_admin/submittal_statuses_controller.rb
class CompanyAdmin::SubmittalStatusesController < CompanyAdmin::CompanyAdminController

  expose(:company) { current_user.company }
  expose(:project)
  expose(:submittal_statuses) {project.submittal_statuses}
  expose(:submittal_status)

  def index
  end

  def new
  end

  def create
    project.submittal_statuses << submittal_status
    if project.save
      redirect_to company_admin_project_submittal_statuses_url(project), :notice => "Submittal Status #{submittal_status.name} was created successfully."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if submittal_status.update_attributes(params[:submittal_status])
      redirect_to company_admin_project_submittal_statuses_url(project), :notice => "Submittal Status #{submittal_status.name} was updated successfully."
    else
      render :edit
    end
  end

  def destroy
    submittal_status.destroy
    redirect_to company_admin_project_submittal_statuses_url(project), :notice => "Submittal Status #{submittal_status.name} was deleted successfully."
  end
end

app/controllers/company_admin/users_controller.rb
class CompanyAdmin::UsersController < CompanyAdmin::CompanyAdminController
  expose(:company) { current_user.company }
  expose(:users) {
    get_users
  }
  expose(:user)

  def index

    respond_to do |format|
      format.html
      format.json { render :json => users.to_json(:only =>[:id, :username]) }
    end
  end

  def new
  end

  def create
    company.users << user
    if company.save
      redirect_to company_admin_users_url, notice: "User #{user.username} was created successfully!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if user.update_attributes(params[:user])
      redirect_to company_admin_users_url, notice: "User #{user.username} was update successfully!"
    else
      render :edit
    end
  end

  def destroy
    user.destroy
    redirect_to company_admin_users_url, notice: "User #{user.username} was deleted successfully!"
  end

  protected

  def get_users
    params[:term].blank? ? User.all : (is_super_admin? ? User.where('username LIKE ?', "%#{params[:term]}%") : User.where('company_id = ? AND username LIKE ?', company.id, "%#{params[:term]}%"))
  end
end

app/helpers/company_admin/customer_helper.rb
module CompanyAdmin::CustomerHelper
end

app/helpers/company_admin/customers_helper.rb
module CompanyAdmin::CustomersHelper
end

app/helpers/company_admin/dashboard_helper.rb
module CompanyAdmin::DashboardHelper
end

app/helpers/company_admin/dashboards_helper.rb
module CompanyAdmin::DashboardsHelper
end

app/helpers/company_admin/pre_requisites_helper.rb
module CompanyAdmin::PreRequisitesHelper
end

app/helpers/company_admin/prerequisites_helper.rb
module CompanyAdmin::PrerequisitesHelper
end

app/helpers/company_admin/project_people_helper.rb
module CompanyAdmin::ProjectPeopleHelper
end

app/helpers/company_admin/project_requirement_types_helper.rb
module CompanyAdmin::ProjectRequirementTypesHelper
end

app/helpers/company_admin/project_types_helper.rb
module CompanyAdmin::ProjectTypesHelper
end

app/helpers/company_admin/projects_helper.rb
module CompanyAdmin::ProjectsHelper
end

app/views/company_admin/submittal_statuses/_form.html.erb
<%= form_for [:company_admin, project, submittal_status] do |f| %>
  <%= f.error_messages %>
  <div class="fields">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="fields">
    <%= f.label :color %>
    <div class="colorpicker_holder"></div>
    <%= f.hidden_field :color %>
  </div>

  <div class="fields">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>

  <div class="buttons">
    <%= f.submit submittal_status.new_record? ? "Create" : "Update" %> <%= link_to "Cancel", company_admin_project_submittal_statuses_url(project) %>
  </div>
<% end %>

<script>
  $(function () {
    var hidden_field = $("#submittal_status_color");
    $(".colorpicker_holder").ColorPicker({
      color: hidden_field.val().replace("#", ""),
      flat:true,
      onChange:function (hsb, hex, rgb) {
        hidden_field.val("#" + hex);
      },
      onBeforeShow: function () {
        $(this).ColorPickerSetColor(hidden_field.val().replace("#", ""));
      }
    });
  });
</script>

app/views/company_admin/submittal_statuses/edit.html.erb
<% content_for :titlebar do %>
  <h1><%= link_to "Projects", company_admin_projects_url %> > <%= link_to "Project #{project.name}", company_admin_project_url(project) %> > <%= link_to "Submittal Statuses", company_admin_project_submittal_statuses_url(project)  %></h1>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => "company_admin/projects/project_sidebar" %>
<% end %>

<h1>Edit Submittal Status</h1>
<%= render :partial => 'form' %>

app/views/company_admin/submittal_statuses/index.html.erb
<% content_for :titlebar do %>
  <h1><%= link_to "Projects", company_admin_projects_url %> > <%= link_to "Project #{project.name}", company_admin_project_url(project) %> > Submittal Statuses</h1>
  <div class="nav">
    <%= link_to "New Submital Status", new_company_admin_project_submittal_status_url(project) %>
  </div>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => "company_admin/projects/project_sidebar" %>
<% end %>

<table class="grid">
  <tr>
    <th>Name</th>
    <th>Color</th>
    <th>Active</th>
    <th></th>
  </tr>
  <% submittal_statuses.each do |submittal_status| %>
    <tr style="background: <%= submittal_status.color %>">
      <td><%= submittal_status.name %></td>
      <td><%= submittal_status.color %></td>
      <td><%= submittal_status.active %></td>
      <td><%= link_to "Edit", edit_company_admin_project_submittal_status_url(project, submittal_status) %> <%= link_to "Delete", company_admin_project_submittal_status_url(project, submittal_status), :method => :delete, :confirm => "Are you sure you want to delete #{submittal_status.name}?" %></td>
    </tr>
  <% end  %>
</table>

app/views/company_admin/submittal_statuses/new.html.erb
<% content_for :titlebar do %>
  <h1><%= link_to "Projects", company_admin_projects_url %> > <%= link_to "Project #{project.name}", company_admin_project_url(project) %> > <%= link_to "Submittal Statuses", company_admin_project_submittal_statuses_url(project)  %></h1>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => "company_admin/projects/project_sidebar" %>
<% end %>

<h1>New Submittal Status</h1>
<%= render :partial => 'form' %>