config/routes.rb
Nspeed::Application.routes.draw do
  mount RailsAdmin::Engine => '/super_admin', :as => 'rails_admin'

  devise_for :users

  resources :receiving

  resources :projects do
    resources :documents do
      get 'by_requirement', :on => :collection
      resources :document_assets
    end
    resources :materials do
      resources :material_invoices
    end
    resources :submittals
    resources :material_types
    resources :material_lists
  end

  namespace :admin do
    resources :companies
  end

  namespace :company_admin do
    resource :dashboard
    resources :projects do
      resources :project_requirements
      resources :submittal_statuses
      resources :prerequisites
      resources :project_people do
        collection do
          post 'save'
        end
        member do
          delete 'remove'
        end
      end
      get 'roles'
    end
    resources :customers
    resources :project_types
    resources :roles
    resources :users
    resources :material_types
  end

  resources :custom_fields
  root :to => 'dashboard#index'

end

app/models/document.rb
class Document < ActiveRecord::Base
  after_initialize :init

  belongs_to :document_type

  has_and_belongs_to_many :projects
  has_and_belongs_to_many :project_requirements

  has_many :document_assets
  has_many :submittal_documents
  has_many :documents, :through => :submittal_documents

  has_many :material_documents
  has_many :materials, :through => :material_documents

  has_many :role_resources, :as => :resource
  has_many :roles, :through => :role_resources


  accepts_nested_attributes_for :document_assets

  def current_document
    document_assets.order("created_at DESC").first
  end

  def current_document_url
    current_document.asset_url
  end

  private
  def init
    self.active = true if self.active.nil?
  end
end

app/models/document_type.rb
class DocumentType < ActiveRecord::Base
  has_many :documents
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  respond_to :html, :json

  expose(:project)
  expose(:project_requirements) { project.project_requirements }
  expose(:document_types) { DocumentType.all }
  expose(:submittal_statuses) { project.submittal_statuses }
  expose(:documents) {
    if params[:project_requirement_id].nil? || params[:project_requirement_id].empty?
      project.documents
    else
      ProjectRequirement.find(params[:project_requirement_id]).documents
    end
  }
  expose(:document)


  def index
  end

  def by_requirement
    respond_with ProjectRequirement.find(params[:project_requirement_id]).documents.joins("left outer join document_assets  on document_assets.document_id = documents.id").where("document_assets.submittal_status_id is null").order(:name)
  end

  def show
  end

  def new
  end

  def create
    project.documents << document
    if project.save

      unless params[:material_id].blank?
        MaterialDocument.create!(document: document, material: Material.find(params[:material_id]))
      end


      if params[:redirect_to].blank?
        redirect_to project_documents_url(project), :notice => "Document was created successfully!"
      else
        redirect_to params[:redirect_to], :notice => "Document was created successfully!"
      end
    else
      render :new
    end
  end

  def edit
  end

  def update
    params[:document][:project_requirement_ids] ||= []
    if document.update_attributes(params[:document])
      redirect_to project_documents_url(project), :notice => "Document was updated successfully!"
    else
      render :edit
    end
  end

  def destroy
    document.destroy
    redirect_to project_documents_url(project), :notice => "Document was deleted successfully!"
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper

end

app/views/documents/_form.html.erb
<%= form_for [project, document] do |f| %>
  <div class="fields">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="fields">
    <%= f.label :document_type_id %>
    <%= f.collection_select :document_type_id, document_types, :id, :name %>
  </div>

  <div class="fields">
    <h3>Project Requirements</h3>
    <% project_requirements.each do |project_requirement| %>
      <div>
        <%= check_box_tag "document[project_requirement_ids][]", project_requirement.id, document.project_requirements.include?(project_requirement) %>
        <%= project_requirement.name %>
      </div>
    <% end %>
  </div>

  <div class="fields">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="fields">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>

  <div class="buttons">
    <%= f.submit document.new_record? ? "Create" : "Update" %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<% content_for :titlebar do %>
  <h1><%= link_to "Project #{project.name}", project_url(project) %> > <%= link_to "Documents", project_documents_url(project) %></h1>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'projects/project_sidebar' %>
<% end %>

<h1>Edit Document</h1>

<%= render :partial => 'form' %>

app/views/documents/index.html.erb
<% content_for :titlebar do %>
  <h1><%= link_to "Project #{project.name}", project_url(project) %> > Documents</h1>
  <div class="nav">
    <%= link_to "New Document", new_project_document_url(project) %>
  </div>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'projects/project_sidebar' %>
<% end %>


<%= form_tag project_documents_url(project), :method => :get do %>
  <div class="search_area">
    <h3>Search</h3>
    <label>Project
      Requirement</label> <%= select_tag("project_requirement_id", options_from_collection_for_select(project_requirements, :id, :name), {:include_blank => "Show All"}) %>
    <div class="buttons">
      <%= submit_tag "Search" %>
    </div>
  </div>
<% end %>

<table class="grid">
  <tr>
    <th>Name</th>
    <th>Type</th>
    <th>Status</th>
    <th>Customer Response Document</th>
    <th></th>
  </tr>
  <% documents.each do |document| %>
    <tr>
      <td><%= link_to document.name, project_document_url(project, document) %></td>
      <td><%= document.document_type.name  %></td>
      <td><%= document.current_document.nil? || document.current_document.submittal_status.nil? ? "" : document.current_document.submittal_status.name %></td>
      <td>

      </td>
      <td><%= link_to "Edit", edit_project_document_url(project, document) %> <%= link_to "Delete", project_document_url(project, document), :method => :delete, :confirm => "Are you sure you want to delete #{document.name}?" %></td>
    </tr>
  <% end %>
</table>

app/views/documents/new.html.erb
<% content_for :titlebar do %>
  <h1><%= link_to "Project #{project.name}", project_url(project) %> > <%= link_to "Documents", project_documents_url(project) %></h1>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'projects/project_sidebar' %>
<% end %>

<h1>New Document</h1>

<%= render :partial => 'form' %>

app/views/documents/show.html.erb
<% content_for :titlebar do %>
  <h1><%= link_to "Project #{project.name}", project_url(project) %> > <%= link_to "Documents", project_documents_url(project) %></h1>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'projects/project_sidebar' %>
<% end %>

<h1><%= document.name %></h1>


<table class="nobackground">
  <tr>
    <th>Status</th>
    <th>File</th>
    <th>File Uploaded At</th>
    <th>Customer Response</th>
    <th>Customer Response Date</th>
    <th></th>
  </tr>
  <% document.document_assets.order("created_at DESC").each do |document_asset| %>
    <tr style="background: <%= document_asset.submittal_status.nil? ? "": document_asset.submittal_status.color %>">
      <td><%=  document_asset.submittal_status.nil? ? "" : document_asset.submittal_status.name %></td>
      <td><a href="<%= document_asset.asset_url %>" target="_blank"><%=get_file_from_url(document_asset.asset_url) %></a></td>
      <td><%= simple_date(document_asset.created_at) %></td>
      <td>
        <% if document_asset.customer_response_url.length > 0 %>
          <a href="<%= document_asset.customer_response_url %>" target="_blank"><%=get_file_from_url(document_asset.customer_response_url) %></a>
        <% end  %>
      </td>
      <td><%= simple_date_no_time(document_asset.customer_response_date) %></td>
      <td><%= link_to "Edit", edit_project_document_document_asset_url(project, document, document_asset)  %></td>
    </tr>
  <% end %>
</table>

<h3>Upload New Version</h3>
<%= form_for [project, document, DocumentAsset.new] do |f| %>
  <div class="fields">
    <%= f.label :asset_url %>
    <%= f.file_field :asset_url %>
    <%= f.hidden_field :asset_url_cache %>
  </div>
  <div class="buttons">
    <%= f.submit "Upload" %>
  </div>
<% end %>