config/routes.rb
Nspeed::Application.routes.draw do
  mount RailsAdmin::Engine => '/super_admin', :as => 'rails_admin'

  devise_for :users

  resources :receiving

  resources :projects do
    resources :documents do
      get 'by_requirement', :on => :collection
      resources :document_assets
    end
    resources :materials do
      resources :material_invoices
    end
    resources :submittals
    resources :material_types
    resources :material_lists
  end

  namespace :admin do
    resources :companies
  end

  namespace :company_admin do
    resource :dashboard
    resources :projects do
      resources :project_requirements
      resources :submittal_statuses
      resources :prerequisites
      resources :project_people do
        collection do
          post 'save'
        end
        member do
          delete 'remove'
        end
      end
      get 'roles'
    end
    resources :customers
    resources :project_types
    resources :roles
    resources :users
    resources :material_types
  end

  resources :custom_fields
  root :to => 'dashboard#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :company
  belongs_to :customer
  belongs_to :project_type

  has_many :project_requirements
  has_many :prerequisites
  has_many :submittal_statuses
  has_many :material_lists
  has_many :materials, :through => :material_lists


  has_and_belongs_to_many :documents

  has_many :role_resources, :as => :resource
  has_many :roles, :through => :role_resources

  validates_presence_of :name, :company_id, :customer_id, :project_type_id

  scope :all_active, where(:is_active => true)

  serialize :custom_fields, Hash

end

app/models/project_type.rb
class ProjectType < ActiveRecord::Base
  belongs_to :company
  validates_presence_of :name
end

app/controllers/company_admin/company_admin_controller.rb
class CompanyAdmin::CompanyAdminController < ApplicationController

  before_filter :authorize_admin_user

  def authorize_admin_user
    unless (is_super_admin? || is_company_admin?)
      redirect_to root_url, notice: "You aren't authorized."
    end
  end


end

app/controllers/company_admin/customers_controller.rb
class CompanyAdmin::CustomersController < CompanyAdmin::CompanyAdminController
  expose(:company) { current_user.company }
  expose(:customers) { company.customers.paginate(:page => params[:page]) }
  expose(:customer) {
    if params[:id].blank?
      Customer.new
    else
      company.customers.find(params[:id])
    end
  }

  def index

  end

  def show
  end

  def new
  end

  def create
    company.customers << customer
    if company.save
      redirect_to company_admin_customers_path, :notice => "Customer #{customer.name} was created successfully!"
    else
      render :new
    end
  end

  def edit
    customer = company.customers.find(params[:id])
  end

  def update
    if customer.update_attributes(params[:customer])
      redirect_to company_admin_customers_path, :notice => "Customer #{customer.name} was updated successfully!"
    else
      render :edit
    end
  end

  def destroy

  end
end

app/controllers/company_admin/dashboards_controller.rb
class CompanyAdmin::DashboardsController < CompanyAdmin::CompanyAdminController
  def show
  end
end

app/controllers/company_admin/prerequisites_controller.rb
class CompanyAdmin::PrerequisitesController < CompanyAdmin::CompanyAdminController
  expose(:company) { current_user.company}
  expose(:project)

  expose(:prerequisites) {project.prerequisites}
  expose(:prerequisite)

  def index
  end

  def new
  end

  def create
    project.prerequisites << prerequisite
    if project.save
      redirect_to company_admin_project_prerequisites_url(project), :notice => "Prerequisite #{prerequisite.name} was created successfully!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if prerequisite.update_attributes(params[:prerequisite])
      redirect_to company_admin_project_prerequisites_url(project), :notice => "Prerequisite #{prerequisite.name} was updated successfully!"
    else
      render :edit
    end
  end

  def destroy
    prerequisite.destroy
    redirect_to company_admin_project_prerequisites_url(project), :notice => "Prerequisite #{prerequisite.name} was deleted successfully!"
  end
end

app/controllers/company_admin/project_people_controller.rb
class CompanyAdmin::ProjectPeopleController < CompanyAdmin::CompanyAdminController
  expose(:company) { current_user.company }
  expose(:project)

  expose(:all_people) { Person.not_in_project(project) }
  expose(:people) { project.people }
  expose(:person)

  def index
  end

  def save
    params[:ids].each do |id|
      unless project.people.exists?(id)
        project.people << Person.find(id)
      end
    end
    project.save

    redirect_to company_admin_project_project_people_url, :notice => "People were added successfully to the project."
  end

  def remove
    removed_person = project.people.find(params[:id])
    project.people.destroy(params[:id])
    project.save
    redirect_to company_admin_project_project_people_url, :notice => "#{removed_person.first_name} #{removed_person.last_name} was removed successfully."
  end
end

app/controllers/company_admin/project_requirements_controller.rb
class CompanyAdmin::ProjectRequirementsController < CompanyAdmin::CompanyAdminController
  expose(:company) { current_user.company }
  expose(:project)
  expose(:prerequisites) { project.prerequisites }

  expose(:project_requirements) { project.project_requirements }
  expose(:project_requirement)

  def index
  end

  def new
  end

  def create
    project.project_requirements << project_requirement
    if project.save
      redirect_to company_admin_project_project_requirements_url(project), :notice => "Requirement #{project_requirement.name} was created successfully!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if project.update_attributes(params[:project_requirement])
      redirect_to company_admin_project_project_requirements_url(project), :notice => "Requirement #{project_requirement.name} was updated successfully!"
    else
      render :new
    end
  end

  def destroy
    project_requirement.destroy
    redirect_to company_admin_project_project_requirements_url(project), :notice => "Requirement #{project_requirement.name} was deleted successfully!"
  end
end

app/controllers/company_admin/project_types_controller.rb
class CompanyAdmin::ProjectTypesController < CompanyAdmin::CompanyAdminController
  expose(:company) {current_user.company}
  expose(:project_types) {company.project_types.paginate(:page => params[:page])}
  expose(:project_type)

  def index
  end

  def show
  end

  def new
  end

  def create
    company.project_types << project_type
    if company.save
      redirect_to company_admin_project_types_url, :notice => "Project Type #{project_type.name} was created successfully!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if project_type.update_parameters[:project_type]
      redirect_to company_admin_project_types_url, :notice => "Project Type #{project_type.name} was created successfully!"
    else
      render :edit
    end
  end

  def destroy
  end
end

app/controllers/company_admin/projects_controller.rb
class CompanyAdmin::ProjectsController < CompanyAdmin::CompanyAdminController

  expose(:company) {current_user.company}
  expose(:project_types) {company.project_types.order(:name)}
  expose(:customers) {company.customers.order(:name)}
  expose(:projects) {company.projects.order(:name)}
  expose(:project)

  def index
  end

  def show
    
  end

  def new
  end

  def create
    company.projects << project
    if company.save
      save_roles
      redirect_to company_admin_projects_url, :notice => "Project #{project.name} was created successfully!"
    else
      render :new
    end
  end

  def edit
  end

  def update

    project_id = project.id # save for later
    result = false
    project.transaction do
      save_roles
      result = project.update_attributes(params[:project])
    end

    project = Project.find(project_id) # refresh the roles
    if result
      redirect_to company_admin_projects_url, :notice => "Project #{project.name} was updated successfully!"
    else
      render :new
    end
  end

  def destroy
    
  end


  def roles
    if params[:term]
      @roles = Role.find(:all,:conditions => ['company_id = ? AND name LIKE ?', company.id, "%#{params[:term]}%"]).map{|x| {:id => x.id, :name => x.name, :mode => :read}}
    else
      @roles = Role.all
    end

    respond_to do |format|
      format.json { render :json => @roles.to_json(:only =>[:id, :name, :mode]) }
    end
  end


  protected

  def save_roles
    project.roles = []
    RoleResource.where(:resource_id => project).where(:resource_type => 'Project').delete_all
    unless params["table_roles_field_id"].nil?
      i = 0
      while i < params["table_roles_field_id"].length do
        RoleResource.create(:role_id => params["table_roles_field_id"][i], :mode => params["table_roles_field_mode"][i], :resource_id => project.id, :resource_type => "Project")
        i += 1
      end
    end
  end
end

app/controllers/company_admin/submittal_statuses_controller.rb
class CompanyAdmin::SubmittalStatusesController < CompanyAdmin::CompanyAdminController

  expose(:company) { current_user.company }
  expose(:project)
  expose(:submittal_statuses) {project.submittal_statuses}
  expose(:submittal_status)

  def index
  end

  def new
  end

  def create
    project.submittal_statuses << submittal_status
    if project.save
      redirect_to company_admin_project_submittal_statuses_url(project), :notice => "Submittal Status #{submittal_status.name} was created successfully."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if submittal_status.update_attributes(params[:submittal_status])
      redirect_to company_admin_project_submittal_statuses_url(project), :notice => "Submittal Status #{submittal_status.name} was updated successfully."
    else
      render :edit
    end
  end

  def destroy
    submittal_status.destroy
    redirect_to company_admin_project_submittal_statuses_url(project), :notice => "Submittal Status #{submittal_status.name} was deleted successfully."
  end
end

app/controllers/company_admin/users_controller.rb
class CompanyAdmin::UsersController < CompanyAdmin::CompanyAdminController
  expose(:company) { current_user.company }
  expose(:users) {
    get_users
  }
  expose(:user)

  def index

    respond_to do |format|
      format.html
      format.json { render :json => users.to_json(:only =>[:id, :username]) }
    end
  end

  def new
  end

  def create
    company.users << user
    if company.save
      redirect_to company_admin_users_url, notice: "User #{user.username} was created successfully!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if user.update_attributes(params[:user])
      redirect_to company_admin_users_url, notice: "User #{user.username} was update successfully!"
    else
      render :edit
    end
  end

  def destroy
    user.destroy
    redirect_to company_admin_users_url, notice: "User #{user.username} was deleted successfully!"
  end

  protected

  def get_users
    params[:term].blank? ? User.all : (is_super_admin? ? User.where('username LIKE ?', "%#{params[:term]}%") : User.where('company_id = ? AND username LIKE ?', company.id, "%#{params[:term]}%"))
  end
end

app/controllers/projects_controller.rb
class ProjectsController < AuthenticateUserController
  expose(:company) { current_user.company }
  expose(:projects) { accessible_projects }
  expose(:project)

  def index
  end

  def show
    authorize_user(project.company, project)
  end

  def update
    if project.update_attributes(params[:project])
      redirect_to projects_url, :notice => "#{project.name} was updated successfully!"
    else
      render :edit
    end
  end

  def destroy
  end
  
protected

  def accessible_projects
    if is_super_admin?
      project_list = Project.all
    elsif is_company_admin?
      project_list = company.projects
    else
      project_list = []
      company.projects.map { |p|
        if current_user.is_in_roles?(p.roles)
          project_list << p
        end
      }
    end
    project_list
  end
end

app/helpers/company_admin/customer_helper.rb
module CompanyAdmin::CustomerHelper
end

app/helpers/company_admin/customers_helper.rb
module CompanyAdmin::CustomersHelper
end

app/helpers/company_admin/dashboard_helper.rb
module CompanyAdmin::DashboardHelper
end

app/helpers/company_admin/dashboards_helper.rb
module CompanyAdmin::DashboardsHelper
end

app/helpers/company_admin/pre_requisites_helper.rb
module CompanyAdmin::PreRequisitesHelper
end

app/helpers/company_admin/prerequisites_helper.rb
module CompanyAdmin::PrerequisitesHelper
end

app/helpers/company_admin/project_people_helper.rb
module CompanyAdmin::ProjectPeopleHelper
end

app/views/company_admin/projects/_form.html.erb
<%= form_for [:company_admin, project] do |f| %>
  <div class="fields">
    <%= f.label :name, "Project #" %>
    <%= f.text_field :name %>
  </div>
  <div class="fields">
    <%= f.label :project_type_id %>
    <%= f.collection_select(:project_type_id, project_types, :id, :name) %>
  </div>
  <div class="fields">
    <%= f.label :customer_id %>
    <%= f.collection_select(:customer_id, customers, :id, :name) %>
  </div>
  <div class="fields">
    <%= f.label :project_name, "Project" %>
    <%= f.text_field :project_name %>
  </div>
  <div class="fields">
    <%= f.label :purchase_order_number,  "PO #" %>
    <%= f.text_field :purchase_order_number %>
  </div>
  <div class="fields">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="fields">
    <%= f.label :is_active, "Active" %>
    <%= f.check_box :is_active %>
  </div>
  <div id="roles_table" >
    <%= f.label :roles_field, "Roles" %>
  </div>

    <script>
      $("#roles_table").completable_table({
          url:function() {
              return "<%= url %>";
          },
          id:"roles_field",
          heading:["name", "mode"],
          search:"name",
          combos:{'mode':['read','write']},
          values: <%= raw((project.id.blank? ? [] :RoleResource.includes(:role).where(:resource_id => project.id).where(:resource_type => project.class).map{|x| {:id => x.role.id, :name => x.role.name, :mode => x.mode}}).to_json) %>
      })
    </script>

  <div class="buttons">
    <%= f.submit project.new_record? ? "Create" : "Update" %> <%= link_to "Cancel", company_admin_projects_url %>
  </div>
<% end %>

app/views/company_admin/projects/_project.html.erb
<div class="project">
  <h3><%= project.name %></h3>
</div>

app/views/company_admin/projects/_project_sidebar.html.erb
<h2>Project Resources</h2>
<div class="sidebar-section">
  <ul>
    <li><%= link_to "Requirements", company_admin_project_project_requirements_url(project) %></li>
    <li><%= link_to "Prerequisites", company_admin_project_prerequisites_url(project) %></li>
    <li><%= link_to "Submittal Status", company_admin_project_submittal_statuses_url(project) %></li>
  </ul>
</div>

app/views/company_admin/projects/edit.html.erb
<% content_for :titlebar do %>
  <h1><%= link_to company.name, company_admin_dashboard_url %> > <%= link_to "Projects", company_admin_projects_url %></h1>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'company_admin/shared/sidebar' %>
<% end %>

<h1>Edit Project: <%= project.name %></h1>
<%= render :partial => 'form', :locals => {:url => company_admin_project_roles_url(project, :json)} %>

app/views/company_admin/projects/index.html.erb
<% content_for :titlebar do %>
  <h1><%= link_to company.name, company_admin_dashboard_url %> > Projects</h1>
  <div class="nav">
    <%= link_to "New Project", new_company_admin_project_url %>
  </div>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'company_admin/shared/sidebar' %>
<% end %>


<table class="grid">
  <tr>
    <th>Project #</th>
    <th>Customer</th>
    <th>Project</th>
    <th>PO #</th>
    <th></th>
  </tr>
  <% projects.each do |project| %>
    <tr>
      <td><%= link_to project.name, company_admin_project_url(project) %></td>
      <td><%= project.customer.name %></td>
      <td><%= project.project_name %></td>
      <td><%= project.purchase_order_number %></td>

      <td><%= link_to "Edit", edit_company_admin_project_url(project) %></td>
    </tr>
  <% end  %>
</table>

app/views/company_admin/projects/new.html.erb
<% content_for :titlebar do %>
  <h1><%= link_to company.name, company_admin_dashboard_url %> > <%= link_to "Projects", company_admin_projects_url %></h1>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'company_admin/shared/sidebar' %>
<% end %>

<h1>New Project</h1>
<%= render :partial => 'form', :locals => {:url => company_admin_project_roles_url(:json) } %>

app/views/company_admin/projects/show.html.erb
<% content_for :titlebar do %>
  <h1><%= link_to "Projects", company_admin_projects_url %></h1>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'project_sidebar' %>
<% end %>


<h1>Project <%= project.name %></h1>