config/routes.rb
Nspeed::Application.routes.draw do
  mount RailsAdmin::Engine => '/super_admin', :as => 'rails_admin'

  devise_for :users

  resources :receiving

  resources :projects do
    resources :documents do
      get 'by_requirement', :on => :collection
      resources :document_assets
    end
    resources :materials do
      resources :material_invoices
    end
    resources :submittals
    resources :material_types
    resources :material_lists
  end

  namespace :admin do
    resources :companies
  end

  namespace :company_admin do
    resource :dashboard
    resources :projects do
      resources :project_requirements
      resources :submittal_statuses
      resources :prerequisites
      resources :project_people do
        collection do
          post 'save'
        end
        member do
          delete 'remove'
        end
      end
      get 'roles'
    end
    resources :customers
    resources :project_types
    resources :roles
    resources :users
    resources :material_types
  end

  resources :custom_fields
  root :to => 'dashboard#index'

end

app/models/material_list.rb
class MaterialList < ActiveRecord::Base
  belongs_to :project
  belongs_to :document
  belongs_to :material

  #validates_presence_of :project_id, :material_id
  accepts_nested_attributes_for :material
end

app/controllers/material_lists_controller.rb
class MaterialListsController < ApplicationController
  expose(:project)
  expose(:company) { project.company }
  expose(:material_types) { company.material_types.order(:name) }
  expose(:documents) { project.documents.where(document_type_id: DocumentType.find_all_by_name("Drawing")) }
  expose(:material_lists) { MaterialList.where(project_id: project) }
  expose(:material_list) {
    if params[:id].blank?
      MaterialList.new
    else
      MaterialList.find(params[:id])
    end
  }
  expose(:material_status) { MaterialStatus.first }

  def index
  end

  def new
  end

  def create
    if material_list.save
      redirect_to project_material_lists_url(project), notice: "Material #{material_list.material.material_type.name} was added successfully!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if material_list.update_attributes[:material_list]
      redirect_to project_material_lists_url(project), notice: "Material #{material_list.material.material_type.name} was added successfully!"
    else
      render :edit
    end
  end

  def destroy
  end
end

app/views/material_lists/edit.html.erb
<% content_for :titlebar do %>
  <h1><%= link_to "Project #{project.name}", project_url(project) %> > <%= link_to "Bill of Materials", project_material_lists_url(project) %></h1>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'projects/project_sidebar' %>
<% end %>

<h1>Update Material</h1>
<%= form_for [project, material_list], :validate => true  do  |f| %>
  <%= f.error_messages %>

  <div class="fields">
    <%= f.label :document_id %>
    <%= f.collection_select :document_id, documents, :id, :name %>
  </div>
  <%= f.fields_for :material, material_list.material  do |mf| %>
    <%= mf.error_messages %>
    <div class="fields">
      <%= mf.label :material_type_id %>
      <%= mf.collection_select :material_type_id, material_types, :id, :name %>
    </div>
    <div class="fields">
      <%= mf.label :item_number %>
      <%= mf.text_field :item_number %>
    </div>
    <div class="fields">
      <%= mf.label :quantity %>
      <%= mf.text_field :quantity %>
    </div>
    <%= mf.hidden_field :material_status_id, :value => material_status.id %>
    <%= mf.hidden_field :project_id, :value => project.id %>
  <% end %>

  <div class="buttons">
    <%= f.submit material_list.new_record? ? "Create" : "Update" %>
    <%= link_to "Cancel", project_material_lists_url(project) %>
  </div>
<% end %>

app/views/material_lists/index.html.erb
<% content_for :titlebar do %>
  <h1><%= link_to "Project #{project.name}", project_url(project) %> > Bill of Materials</h1>
  <div class="nav">
    <%= link_to "New Bill Of Materials", new_project_material_list_url(project) %>
  </div>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'projects/project_sidebar' %>
<% end %>


<table>
  <tr>
    <th>Line Number</th>
    <th>Material</th>
    <th>Quantity</th>
    <th></th>
  </tr>
  <% documents.each do |document| %>
    <tr style="background:#cdcdcd;">
      <td colspan="4">Drawing:  <%= link_to document.name, project_document_url(project, document) %></td>
    </tr>
    
    <% material_lists.where(document_id: document).joins(:material).order('item_number ASC').each do |material_list| %>
      <tr>
        <td><%= material_list.material.item_number %></td>
        <td><%= material_list.material.material_type.name %></td>
        <td><%= material_list.material.quantity %></td>
        <td><%= link_to 'Edit', edit_project_material_list_url(project, material_list) %> | <%= link_to 'Delete', project_material_list_url(project, material_list), :method => :delete, :confirm => "Are you sure you want to delete #{material_list.material.material_type.name}?" %></td>
      </tr>
    <% end %>
  <% end %>
</table>



<script>

</script>

app/views/material_lists/new.html.erb
<% content_for :titlebar do %>
  <h1><%= link_to "Project #{project.name}", project_url(project) %> > <%= link_to "Bill of Materials", project_material_lists_url(project) %></h1>

<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'projects/project_sidebar' %>
<% end %>

<h1>New Material</h1>
<%= form_for [project, material_list], :validate => true  do  |f| %>
  <%= f.error_messages %>

  <div class="fields">
    <%= f.label :document_id %>
    <%= f.collection_select :document_id, documents, :id, :name %>
  </div>
  <%= f.fields_for :material, Material.new  do |mf| %>
    <%= mf.error_messages %>
    <div class="fields">
      <%= mf.label :material_type_id %>
      <%= mf.collection_select :material_type_id, material_types, :id, :name %>
    </div>
    <div class="fields">
      <%= mf.label :item_number %>
      <%= mf.text_field :item_number %>
    </div>
    <div class="fields">
      <%= mf.label :quantity %>
      <%= mf.text_field :quantity %>
    </div>
    <%= mf.hidden_field :material_status_id, :value => material_status.id %>
    <%= mf.hidden_field :project_id, :value => project.id %>
  <% end %>
  <%= f.hidden_field :project_id, :value => project.id %>
  <div class="buttons">
    <%= f.submit material_list.new_record? ? "Create" : "Update" %>
    <%= link_to "Cancel", project_material_lists_url(project) %>
  </div>
<% end %>